"""CI guard: the README TEST-BADGE version must match the package version.

The badge block (rendered by ``scripts/update_test_badge.py``) stamps the
package version. It is regenerated by hand / on release, so it silently drifts
when a release bumps the version but nobody re-runs the badge script — which is
exactly how the badge sat at ``v0.8.5`` while the package shipped ``v0.8.38``.

This guard fails on that drift. It checks ONLY the version (not the test count
or coverage, which legitimately change on every commit and would make the gate
flap). It mirrors ``test_no_placeholder_cves.py``: a cheap, offline, structural
invariant — not a full re-run of the badge generator.

Fix on failure: ``python3 scripts/update_test_badge.py`` (or ``make test-badge``).
"""

from __future__ import annotations

import re
from pathlib import Path

_ROOT = Path(__file__).resolve().parents[1]
_README = _ROOT / "README.md"
_INIT = _ROOT / "src" / "agent_airlock" / "__init__.py"
_PYPROJECT = _ROOT / "pyproject.toml"

_BADGE_BLOCK_RE = re.compile(
    r"<!-- TEST-BADGE-START -->(?P<body>.*?)<!-- TEST-BADGE-END -->",
    re.DOTALL,
)
_BADGE_VERSION_RE = re.compile(r"\bv(?P<version>\d+\.\d+\.\d+[^\s*]*)")


def _package_version() -> str:
    m = re.search(r'__version__\s*=\s*"([^"]+)"', _INIT.read_text(encoding="utf-8"))
    assert m, "could not read __version__ from __init__.py"
    return m.group(1)


def _pyproject_version() -> str:
    m = re.search(r'^version\s*=\s*"([^"]+)"', _PYPROJECT.read_text(encoding="utf-8"), re.MULTILINE)
    assert m, "could not read version from pyproject.toml"
    return m.group(1)


def _badge_version() -> str:
    block = _BADGE_BLOCK_RE.search(_README.read_text(encoding="utf-8"))
    assert block, "README is missing the TEST-BADGE block"
    m = _BADGE_VERSION_RE.search(block.group("body"))
    assert m, "TEST-BADGE block has no vX.Y.Z version stamp"
    return m.group("version")


def test_package_and_pyproject_version_agree() -> None:
    assert _package_version() == _pyproject_version(), (
        "__init__.py and pyproject.toml versions disagree — fix before release"
    )


def test_badge_version_matches_package_version() -> None:
    badge, pkg = _badge_version(), _package_version()
    assert badge == pkg, (
        f"README test-badge shows v{badge} but the package is v{pkg}. "
        f"Run `python3 scripts/update_test_badge.py` to refresh the badge."
    )
