"""Tests for the v0.8.3 ``classify_sdk_lineage`` SDK-provenance classifier.

Honest scope
------------
This module is a **pure-function classifier**. It does NOT intercept
HTTP, proxy MCP servers, or run automatically — it's a building
block operators call from their own audit hooks. agent-airlock's
``@Airlock`` decorator wraps a Python tool function and never sees
outbound HTTP headers itself; the architecture is decorator-in-process,
not proxy/sidecar (a deliberate anti-pivot design rule).

Anchor
------
Anthropic announced the acquisition of Stainless on 2026-05-13 and
the wind-down of hosted Stainless products, including the SDK
generator (https://www.anthropic.com/news/anthropic-acquires-stainless).
Operators wanting visibility into which MCP servers in their
inventory were generated by the deprecated Stainless toolchain can
call ``classify_sdk_lineage(...)`` from their own audit hooks and
tag the result onto trajectory events.
"""

from __future__ import annotations

import pytest

from agent_airlock.sdk_provenance import (
    DEFAULT_STAINLESS_BODY_MARKERS,
    DEFAULT_STAINLESS_UA_PATTERNS,
    SDKLineage,
    SDKLineageMatch,
    classify_sdk_lineage,
)


class TestUserAgentDetection:
    """User-Agent header carries an explicit Stainless marker."""

    def test_stainless_ua_lowercase(self) -> None:
        m = classify_sdk_lineage(user_agent="stainless-node/0.42.0", response_body_head=None)
        assert isinstance(m, SDKLineageMatch)
        assert m.lineage == SDKLineage.STAINLESS
        assert m.match_source == "user_agent"
        assert m.matched_pattern is not None

    def test_stainless_ua_titlecase(self) -> None:
        m = classify_sdk_lineage(user_agent="Stainless-Python/1.2", response_body_head=None)
        assert m.lineage == SDKLineage.STAINLESS
        assert m.match_source == "user_agent"

    def test_stainless_ua_substring(self) -> None:
        """The marker is found even when surrounded by other UA text."""
        m = classify_sdk_lineage(
            user_agent="myapp/1.0 stainless-sdk/0.3 (linux)",
            response_body_head=None,
        )
        assert m.lineage == SDKLineage.STAINLESS


class TestResponseBodyDetection:
    """Code-gen banner in the first bytes of a server response."""

    def test_body_banner_detected(self) -> None:
        body = (
            "// This file was auto-generated by Stainless. Do not edit.\nclass MCPServer:\n    ..."
        )
        m = classify_sdk_lineage(user_agent=None, response_body_head=body)
        assert m.lineage == SDKLineage.STAINLESS
        assert m.match_source == "response_body"

    def test_body_python_generator_comment(self) -> None:
        body = "# Generated by Stainless\ndef foo(): pass"
        m = classify_sdk_lineage(user_agent=None, response_body_head=body)
        assert m.lineage == SDKLineage.STAINLESS

    def test_user_agent_takes_priority_when_both_match(self) -> None:
        """A UA match short-circuits before scanning the body."""
        m = classify_sdk_lineage(
            user_agent="stainless-node/1.0",
            response_body_head="// Generated by Stainless",
        )
        assert m.lineage == SDKLineage.STAINLESS
        assert m.match_source == "user_agent"


class TestNoMatch:
    """When neither source carries a Stainless marker the lineage is UNKNOWN."""

    def test_both_inputs_none(self) -> None:
        m = classify_sdk_lineage(user_agent=None, response_body_head=None)
        assert m.lineage == SDKLineage.UNKNOWN
        assert m.match_source is None
        assert m.matched_pattern is None

    def test_unrelated_ua(self) -> None:
        m = classify_sdk_lineage(user_agent="curl/7.79.1", response_body_head=None)
        assert m.lineage == SDKLineage.UNKNOWN

    def test_unrelated_body(self) -> None:
        m = classify_sdk_lineage(
            user_agent=None,
            response_body_head='{"hello":"world","name":"FastMCP"}',
        )
        assert m.lineage == SDKLineage.UNKNOWN

    def test_empty_strings(self) -> None:
        m = classify_sdk_lineage(user_agent="", response_body_head="")
        assert m.lineage == SDKLineage.UNKNOWN


class TestEdgeCases:
    """Truncated input, non-string types, etc."""

    def test_truncated_body_before_marker(self) -> None:
        """If the marker would have been further in the response, we miss it."""
        body = "// some header line\n" * 200  # 4000+ chars of decoy
        m = classify_sdk_lineage(user_agent=None, response_body_head=body)
        assert m.lineage == SDKLineage.UNKNOWN

    def test_case_insensitive_match(self) -> None:
        """Stainless marker matching is case-insensitive."""
        m = classify_sdk_lineage(user_agent="STAINLESS-SDK/0.1", response_body_head=None)
        assert m.lineage == SDKLineage.STAINLESS


class TestMatchShape:
    """The match dataclass is frozen and mirrors the v0.8.x decision family."""

    def test_match_is_frozen(self) -> None:
        m = classify_sdk_lineage(user_agent="stainless-node", response_body_head=None)
        with pytest.raises((AttributeError, Exception)):  # FrozenInstanceError
            m.lineage = SDKLineage.UNKNOWN  # type: ignore[misc]

    def test_match_detail_is_string(self) -> None:
        m = classify_sdk_lineage(user_agent="stainless-node", response_body_head=None)
        assert isinstance(m.detail, str)
        assert m.detail


class TestDefaultPatternSets:
    """The default Stainless pattern sets are public for operator overrides."""

    def test_default_ua_patterns_is_frozenset(self) -> None:
        assert isinstance(DEFAULT_STAINLESS_UA_PATTERNS, frozenset)
        assert "stainless" in DEFAULT_STAINLESS_UA_PATTERNS

    def test_default_body_markers_is_tuple(self) -> None:
        assert isinstance(DEFAULT_STAINLESS_BODY_MARKERS, tuple)
        assert any("Stainless" in m for m in DEFAULT_STAINLESS_BODY_MARKERS)


class TestOperatorPatternOverride:
    """Operators can extend the marker patterns."""

    def test_extra_ua_pattern_propagates(self) -> None:
        m = classify_sdk_lineage(
            user_agent="acme-internal-gen/1.0",
            response_body_head=None,
            extra_ua_patterns=frozenset({"acme-internal-gen"}),
        )
        assert m.lineage == SDKLineage.STAINLESS  # operator opted in to flag
        assert m.matched_pattern == "acme-internal-gen"

    def test_extra_body_pattern_propagates(self) -> None:
        m = classify_sdk_lineage(
            user_agent=None,
            response_body_head="// generated by AcmeCodeGen v3",
            extra_body_markers=("AcmeCodeGen",),
        )
        assert m.lineage == SDKLineage.STAINLESS
        assert m.match_source == "response_body"


class TestFactoryShape:
    """``policy_presets.stainless_provenance_probe_defaults`` factory."""

    def test_factory_is_importable(self) -> None:
        from agent_airlock.policy_presets import stainless_provenance_probe_defaults

        assert callable(stainless_provenance_probe_defaults)

    def test_factory_returns_expected_shape(self) -> None:
        from agent_airlock.policy_presets import stainless_provenance_probe_defaults

        cfg = stainless_provenance_probe_defaults()
        assert cfg["preset_id"] == "stainless_provenance_probe_2026_05_19"
        assert cfg["severity"] == "info"  # visibility, not enforcement
        assert cfg["default_action"] == "tag_only"
        assert "anthropic.com" in cfg["advisory_url"]
        assert isinstance(cfg["ua_patterns"], frozenset)
        assert "stainless" in cfg["ua_patterns"]
        assert isinstance(cfg["body_markers"], tuple)
