"""Regression tests for public-facing metadata drift (v0.5.4+).

These tests guard against the exact bugs fixed in v0.5.4:

1. ``pyproject.toml [project.urls]`` carried a single-``j`` ``sattyamjain``
   slug on Homepage / Documentation / Repository / Issues. The real GitHub
   org is ``sattyamjjain`` (double-j), so every PyPI landing-page link was
   404'd. Asserting the canonical slug in every URL prevents the typo
   from sneaking back in.
2. The ``README.md`` ``Performance`` table claimed ``1,157 passing``
   while the auto-generated ``TEST-BADGE`` block directly above it
   already read ``1,540 tests``. Two sources of truth disagreed with
   each other. The fix removes the hand-maintained row; this test keeps
   the stale number from re-appearing.

Both assertions are cheap and pure-Python; no pytest fixtures.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

# tomllib is stdlib on 3.11+; fall back to the tomli extra for 3.10
# (already a declared dependency via pyproject.toml:43).
if sys.version_info >= (3, 11):
    import tomllib
else:  # pragma: no cover
    import tomli as tomllib

PROJECT_ROOT = Path(__file__).resolve().parent.parent
PYPROJECT = PROJECT_ROOT / "pyproject.toml"
README = PROJECT_ROOT / "README.md"

CANONICAL_GITHUB_SLUG = "sattyamjjain"  # double-j — the real org
STALE_TEST_COUNT = "1,157 passing"


def _load_pyproject() -> dict:
    with PYPROJECT.open("rb") as fh:
        return tomllib.load(fh)


def test_project_urls_point_to_canonical_repo() -> None:
    """Every [project.urls] entry must contain the canonical ``sattyamjjain`` slug."""
    data = _load_pyproject()
    urls = data["project"]["urls"]
    assert urls, "pyproject.toml [project.urls] is empty — PyPI landing page will have no links"
    for name, url in urls.items():
        assert CANONICAL_GITHUB_SLUG in url, (
            f"[project.urls].{name} = {url!r} does not contain "
            f"canonical slug {CANONICAL_GITHUB_SLUG!r} — likely the single-``j`` "
            "typo from v0.5.3 has crept back in"
        )


def test_readme_no_contradicting_test_count() -> None:
    """README must not hand-maintain a test count — TEST-BADGE block is authoritative."""
    text = README.read_text(encoding="utf-8")
    assert STALE_TEST_COUNT not in text, (
        f"README.md still contains the stale {STALE_TEST_COUNT!r} row. "
        "The TEST-BADGE block (regenerated by scripts/update_test_badge.py) is "
        "the only sanctioned source of test-count truth."
    )


def test_readme_integration_count_matches_examples() -> None:
    """README Performance table's 'Framework integrations' must equal the row count in 'Complete Examples'.

    Honesty bug from v0.5.5: Performance row hardcoded 9 while the
    Complete Examples table at line ~538 listed 10 frameworks
    (Claude Agent SDK was added in v0.5.1 but the metric never
    caught up). This test scrapes the example table and asserts the
    Performance row tracks it, so neither side can drift again.
    """
    text = README.read_text(encoding="utf-8")
    # Find the Complete Examples section and count its data rows.
    marker = "### Complete Examples"
    idx = text.find(marker)
    assert idx >= 0, "README is missing the '### Complete Examples' section"
    # Stop at the next ## or ### heading.
    rest = text[idx + len(marker) :]
    next_section = re.search(r"\n#+ ", rest)
    block = rest if next_section is None else rest[: next_section.start()]
    # Count rows that look like a Markdown data row beginning with "| Something | ..."
    # but skip the header and separator rows.
    data_rows = [
        line
        for line in block.splitlines()
        if line.startswith("|")
        and not line.startswith("| Framework |")
        and not line.startswith("|---")
    ]
    actual_count = len(data_rows)
    # Performance table row.
    perf_match = re.search(r"\|\s*\*\*Framework integrations\*\*\s*\|\s*(\d+)\s*\|", text)
    assert perf_match, "README Performance table is missing the 'Framework integrations' row"
    claimed = int(perf_match.group(1))
    assert claimed == actual_count, (
        f"README claims {claimed} framework integrations but Complete Examples "
        f"table has {actual_count} rows. Fix one or the other."
    )


def test_python_version_matches_pyproject() -> None:
    """Sanity-check: the Python interpreter running the test suite meets the floor."""
    data = _load_pyproject()
    requires = data["project"]["requires-python"]
    # "requires-python = ">=3.10"" → we only assert the pin is parseable and real.
    assert requires.startswith(">="), f"requires-python {requires!r} must start with '>='"
    min_version = requires.removeprefix(">=").strip()
    major, minor = (int(x) for x in min_version.split(".", 1))
    # Running interpreter must satisfy the declared floor — defensive guard for
    # contributors on very old stacks.
    assert sys.version_info >= (major, minor), (
        f"Python {sys.version_info.major}.{sys.version_info.minor} is below the "
        f"declared floor {min_version}"
    )
