"""Human-oversight decorator (v0.8.4+, Code-as-Harness survey anchor).

What this module ships
----------------------
A decorator factory ``@requires_human_oversight(approver=...)`` that
gates a tool function on an operator-supplied approval callable.
The decorator builds a structured :class:`OversightRequest`, hands
it to the approver, and acts on the returned
:class:`OversightResponse` — calling the wrapped function on
``GRANT``, raising :class:`OversightDeniedError` on ``DENY``, or
:class:`OversightTimeoutError` on ``TIMEOUT``.

What this module does NOT ship
------------------------------
- An ``audit_emitter.await_response`` bidirectional RPC channel.
  The 2026-05-20 Product Improvements doc proposed grafting a
  request/response channel onto the existing one-way audit emitter.
  That would have invented a new transport abstraction inside
  agent-airlock. Instead, the **operator supplies the transport**
  via the ``approver`` callable; agent-airlock ships the decorator
  + data shapes only.
- Slack / PagerDuty / CLI integration. Operators wire these into
  their own approver callable.
- Async wrapping. v0.8.4 ships the sync surface. Async support is
  a deferred follow-up that needs a separate API design pass.

Why the operator-supplied-approver shape
----------------------------------------
agent-airlock's existing primitives are all building blocks
operators compose (``vaccinate_openapi(spec)``,
``classify_sdk_lineage(...)``, ``OpenAPIDriftGuard(spec=...)``).
This decorator follows the same pattern: agent-airlock provides
the gate + the protocol shapes; the operator wires the transport.

Anchor
------
Code-as-Harness survey (arXiv:2605.18747, Ning et al., 2026-05-18)
identifies "human oversight for safety-critical actions" as an
open challenge in harness engineering. This module is a primitive
operators can use to address that challenge for tool calls in
their own harness.

Primary source
--------------
https://arxiv.org/abs/2605.18747
"""

from __future__ import annotations

import datetime as _dt
import enum
import functools
import uuid
from collections.abc import Callable, Mapping
from dataclasses import dataclass, field
from typing import Any, TypeVar

import structlog

logger = structlog.get_logger("agent-airlock.oversight")


F = TypeVar("F", bound=Callable[..., Any])


class OversightVerdict(str, enum.Enum):
    """Stable verdict labels returned by an approver."""

    GRANT = "grant"
    DENY = "deny"
    TIMEOUT = "timeout"


@dataclass(frozen=True)
class OversightRequest:
    """Structured approval request handed to the operator-supplied approver.

    Attributes:
        request_id: A UUID4 string (generated by the decorator) that
            the approver MUST echo on its :class:`OversightResponse`.
        tool_name: ``__name__`` of the wrapped function.
        args: Dict with two keys: ``"args"`` (positional, tuple) and
            ``"kwargs"`` (keyword, mapping). The approver inspects
            this to decide whether to grant.
        channel: Free-form hint passed through from the decorator
            ``channel=`` argument (e.g. ``"prod-deploys"``,
            ``"finance"``). The approver interprets this however
            its transport requires.
        timeout_seconds: Wall-clock timeout the operator declared
            on the decorator. Echoed onto the request so the
            approver can use it for its own poll loops if it wants.
        requested_at: ISO 8601 UTC timestamp when the gate fired.
    """

    request_id: str
    tool_name: str
    args: Mapping[str, Any]
    channel: str
    timeout_seconds: float
    requested_at: str


@dataclass(frozen=True)
class OversightResponse:
    """Approver's reply.

    Attributes:
        request_id: MUST match the originating
            :attr:`OversightRequest.request_id`. A mismatch is treated
            as a protocol fault and raises ``ValueError``.
        verdict: :class:`OversightVerdict.GRANT` / ``DENY`` / ``TIMEOUT``.
        detail: Free-form explanation suitable for audit logs.
        approver: Optional identifier of the human/system that
            decided (e.g. ``"alice@example.com"``, ``"pagerduty-bot"``).
    """

    request_id: str
    verdict: OversightVerdict
    detail: str = ""
    approver: str | None = None


Approver = Callable[[OversightRequest], OversightResponse]
"""The operator-supplied callable signature."""

AuditEmitter = Callable[[str, Mapping[str, Any]], None]
"""Optional one-way emitter for ``oversight.request|grant|deny`` events.

This is a *one-way* sink, matching agent-airlock's existing emitter
shape. It does NOT support request/response RPC — that lives in the
:class:`Approver` callable.
"""


class OversightDeniedError(Exception):
    """Raised by a decorated function when the approver returns ``DENY``.

    Attributes:
        request: The :class:`OversightRequest` that was denied.
        response: The :class:`OversightResponse` that denied it.
    """

    def __init__(self, request: OversightRequest, response: OversightResponse) -> None:
        self.request = request
        self.response = response
        super().__init__(
            f"tool {request.tool_name!r} denied by oversight (approver={response.approver!r}): "
            f"{response.detail}"
        )


class OversightTimeoutError(TimeoutError):
    """Raised when the approver returns ``TIMEOUT`` (or doesn't respond in time).

    Attributes:
        request: The :class:`OversightRequest` that timed out.
    """

    def __init__(self, request: OversightRequest) -> None:
        self.request = request
        super().__init__(
            f"oversight gate timed out for tool {request.tool_name!r} "
            f"after {request.timeout_seconds:.1f}s"
        )


def requires_human_oversight(
    *,
    approver: Approver,
    channel: str = "default",
    timeout_seconds: float = 300.0,
    audit_emitter: AuditEmitter | None = None,
) -> Callable[[F], F]:
    """Decorator factory: gate a tool function on operator-supplied approval.

    Args:
        approver: Operator-supplied callable that receives an
            :class:`OversightRequest` and returns an
            :class:`OversightResponse`. The operator wires this to
            whatever transport they want (Slack, PagerDuty, CLI
            prompt, in-process recorded responses for tests, …).
        channel: Free-form hint passed through to the approver on
            :attr:`OversightRequest.channel`. Useful for routing
            in transports that have multiple endpoints.
        timeout_seconds: Wall-clock budget declared on the request.
            Echoed to the approver via
            :attr:`OversightRequest.timeout_seconds`; the approver
            is responsible for honouring it.
        audit_emitter: Optional one-way callable that receives
            ``("oversight.request"|"oversight.grant"|"oversight.deny",
            payload_dict)`` for every gate firing. Useful for OTel /
            JSON-Lines audit trails. Defaults to ``None`` (events
            still go through the module structlog logger).

    Returns:
        A decorator that wraps any sync callable.

    Raises:
        TypeError: ``approver`` is not callable.
        ValueError: ``timeout_seconds`` is negative.
    """
    if not callable(approver):
        raise TypeError(f"approver must be callable; got {type(approver).__name__}")
    if timeout_seconds < 0.0:
        raise ValueError(f"timeout_seconds must be non-negative; got {timeout_seconds!r}")

    def decorator(fn: F) -> F:
        @functools.wraps(fn)
        def wrapped(*args: Any, **kwargs: Any) -> Any:
            request = OversightRequest(
                request_id=str(uuid.uuid4()),
                tool_name=fn.__name__,
                args={"args": args, "kwargs": dict(kwargs)},
                channel=channel,
                timeout_seconds=float(timeout_seconds),
                requested_at=_dt.datetime.now(_dt.timezone.utc).isoformat(),
            )
            _emit(
                audit_emitter,
                "oversight.request",
                {
                    "request_id": request.request_id,
                    "tool_name": request.tool_name,
                    "channel": request.channel,
                    "timeout_seconds": request.timeout_seconds,
                    "requested_at": request.requested_at,
                },
            )

            response = approver(request)
            if response.request_id != request.request_id:
                raise ValueError(
                    f"approver returned a response with mismatched request_id: "
                    f"expected {request.request_id!r}, got {response.request_id!r}"
                )

            if response.verdict is OversightVerdict.GRANT:
                _emit(
                    audit_emitter,
                    "oversight.grant",
                    {
                        "request_id": request.request_id,
                        "tool_name": request.tool_name,
                        "approver": response.approver,
                        "detail": response.detail,
                    },
                )
                return fn(*args, **kwargs)

            if response.verdict is OversightVerdict.DENY:
                _emit(
                    audit_emitter,
                    "oversight.deny",
                    {
                        "request_id": request.request_id,
                        "tool_name": request.tool_name,
                        "approver": response.approver,
                        "detail": response.detail,
                    },
                )
                raise OversightDeniedError(request=request, response=response)

            # OversightVerdict.TIMEOUT
            _emit(
                audit_emitter,
                "oversight.timeout",
                {
                    "request_id": request.request_id,
                    "tool_name": request.tool_name,
                    "timeout_seconds": request.timeout_seconds,
                },
            )
            raise OversightTimeoutError(request=request)

        return wrapped  # type: ignore[return-value]

    return decorator


def _emit(
    emitter: AuditEmitter | None,
    event_type: str,
    payload: Mapping[str, Any],
) -> None:
    """Fan out one structured event to the operator emitter + the module logger."""
    logger.info(event_type.replace(".", "_"), **payload)
    if emitter is not None:
        emitter(event_type, dict(payload))


@dataclass
class InProcessRecordedApprover:
    """Bundled testing helper — returns pre-set verdicts per tool name.

    Designed for unit-test scaffolding. Holds a ``decisions`` mapping
    of ``tool_name -> OversightVerdict``. When asked about a tool not
    in the mapping, defaults to :attr:`OversightVerdict.TIMEOUT` so
    tests fail loudly on unexpected calls rather than silently passing.

    The approver also records every :class:`OversightRequest` it
    received on the ``calls`` list, so tests can assert call shapes.

    Attributes:
        decisions: ``{tool_name: OversightVerdict}``.
        calls: Append-only list of every request received.
    """

    decisions: Mapping[str, OversightVerdict]
    calls: list[OversightRequest] = field(default_factory=list)

    def __call__(self, request: OversightRequest) -> OversightResponse:
        self.calls.append(request)
        verdict = self.decisions.get(request.tool_name, OversightVerdict.TIMEOUT)
        return OversightResponse(
            request_id=request.request_id,
            verdict=verdict,
            detail=f"InProcessRecordedApprover: {verdict.value}",
            approver="InProcessRecordedApprover",
        )


__all__ = [
    "Approver",
    "AuditEmitter",
    "InProcessRecordedApprover",
    "OversightDeniedError",
    "OversightRequest",
    "OversightResponse",
    "OversightTimeoutError",
    "OversightVerdict",
    "requires_human_oversight",
]
