"""SDK provenance classifier (v0.8.3+, Stainless-acquisition anchor).

What this module is
-------------------
A **pure-function classifier** that scans an MCP-server User-Agent
header and the first bytes of a response body for markers indicating
the server was generated by a specific SDK toolchain. The classifier
is *opt-in*: operators call :func:`classify_sdk_lineage` from their
own audit hooks; agent-airlock does NOT intercept HTTP or proxy MCP
servers itself.

What this module is NOT
-----------------------
This is NOT a runtime probe, proxy, or sidecar. agent-airlock's
``@Airlock`` decorator wraps a Python tool function the agent calls;
it never sees outbound HTTP response headers on its own. The
``decorator-in-process`` model is a deliberate anti-pivot choice
(in-process decorator, not a proxy/sidecar).

The visibility surface added here is a **building block**: a tool
function that itself calls out to an MCP server can pass the
response's UA / first bytes through this classifier and tag the
result onto the trajectory event.

Anchor
------
Anthropic announced the acquisition of Stainless on 2026-05-13 and
the wind-down of hosted Stainless products, including the SDK
generator. Operators wanting visibility into which MCP servers in
their inventory were generated by the deprecated Stainless toolchain
can use this classifier.

Primary source
--------------
https://www.anthropic.com/news/anthropic-acquires-stainless
"""

from __future__ import annotations

import enum
from dataclasses import dataclass

import structlog

logger = structlog.get_logger("agent-airlock.sdk_provenance")


# Default Stainless markers — case-insensitive substring matches on
# the User-Agent header. Operators extend via ``extra_ua_patterns``.
DEFAULT_STAINLESS_UA_PATTERNS: frozenset[str] = frozenset(
    {
        "stainless",
        "stainless-sdk",
        "stainless-node",
        "stainless-python",
    }
)


# Default code-gen banner patterns for the response body head.
# Each entry is a literal substring scanned against the first
# ``_BODY_SCAN_BYTES`` of the response. Operators extend via
# ``extra_body_markers``.
DEFAULT_STAINLESS_BODY_MARKERS: tuple[str, ...] = (
    "auto-generated by Stainless",
    "Generated by Stainless",
    "@stainless-generated",
    "stainless-codegen",
)


# Only the first ~4KB of a response is scanned. A code-gen banner
# appearing past that point is missed by design — operators paying
# for a deeper scan can extend ``extra_body_markers`` and feed a
# larger ``response_body_head``.
_BODY_SCAN_BYTES = 4096


class SDKLineage(str, enum.Enum):
    """Stable lineage labels emitted by :func:`classify_sdk_lineage`."""

    STAINLESS = "stainless"
    UNKNOWN = "unknown"


@dataclass(frozen=True)
class SDKLineageMatch:
    """Outcome of a single :func:`classify_sdk_lineage` call.

    Mirrors the v0.7.x / v0.8.x decision family shape — pure data,
    frozen, suitable for serialisation onto a trajectory event.

    Attributes:
        lineage: Stable :class:`SDKLineage` value.
        match_source: ``"user_agent"`` / ``"response_body"`` /
            ``None`` (when lineage is :attr:`SDKLineage.UNKNOWN`).
        matched_pattern: The exact pattern that fired, or ``None``.
        detail: Free-form explanation for logs.
    """

    lineage: SDKLineage
    match_source: str | None
    matched_pattern: str | None
    detail: str


def classify_sdk_lineage(
    *,
    user_agent: str | None,
    response_body_head: str | None,
    extra_ua_patterns: frozenset[str] = frozenset(),
    extra_body_markers: tuple[str, ...] = (),
) -> SDKLineageMatch:
    """Classify a server's SDK provenance from its UA + response head.

    Detection order: User-Agent first (cheap and definitive), then
    body-marker scan over the first ``_BODY_SCAN_BYTES`` bytes.
    Case-insensitive substring matching on both surfaces. A UA match
    short-circuits — the body is not scanned.

    Args:
        user_agent: The server's ``User-Agent`` header, or ``None``.
        response_body_head: The first bytes of the server's response
            body, or ``None``. Only the first 4096 bytes are scanned.
        extra_ua_patterns: Additional UA-header substrings to flag
            on top of :data:`DEFAULT_STAINLESS_UA_PATTERNS`.
        extra_body_markers: Additional body-banner substrings to flag
            on top of :data:`DEFAULT_STAINLESS_BODY_MARKERS`.

    Returns:
        :class:`SDKLineageMatch`. A non-Stainless match yields
        :attr:`SDKLineage.UNKNOWN` with ``match_source=None``.
    """
    ua_patterns = DEFAULT_STAINLESS_UA_PATTERNS | extra_ua_patterns
    body_markers = DEFAULT_STAINLESS_BODY_MARKERS + extra_body_markers

    # 1) User-Agent scan (case-insensitive substring).
    if user_agent:
        ua_lower = user_agent.lower()
        for pattern in sorted(ua_patterns):
            if pattern.lower() in ua_lower:
                logger.info(
                    "sdk_lineage_match",
                    source="user_agent",
                    pattern=pattern,
                    lineage="stainless",
                )
                return SDKLineageMatch(
                    lineage=SDKLineage.STAINLESS,
                    match_source="user_agent",
                    matched_pattern=pattern,
                    detail=(f"User-Agent {user_agent!r} matches Stainless pattern {pattern!r}"),
                )

    # 2) Body-marker scan (case-insensitive substring, first 4KB).
    if response_body_head:
        head = response_body_head[:_BODY_SCAN_BYTES]
        head_lower = head.lower()
        for marker in body_markers:
            if marker.lower() in head_lower:
                logger.info(
                    "sdk_lineage_match",
                    source="response_body",
                    pattern=marker,
                    lineage="stainless",
                )
                return SDKLineageMatch(
                    lineage=SDKLineage.STAINLESS,
                    match_source="response_body",
                    matched_pattern=marker,
                    detail=f"response body head contains Stainless marker {marker!r}",
                )

    return SDKLineageMatch(
        lineage=SDKLineage.UNKNOWN,
        match_source=None,
        matched_pattern=None,
        detail="no Stainless markers found in User-Agent or response body head",
    )


__all__ = [
    "DEFAULT_STAINLESS_BODY_MARKERS",
    "DEFAULT_STAINLESS_UA_PATTERNS",
    "SDKLineage",
    "SDKLineageMatch",
    "classify_sdk_lineage",
]
