"""Policy-bundle lockfile (``policy_bundle.lock``) — v0.6.0+.

``airlock pack lock`` emits a TOML lockfile listing every active
preset with a SHA-256 of its canonical form, and ``airlock replay
--bundle-lock`` refuses to run if any preset hash drifted from the
lock — so a CI bot, a compliance audit, and a paid-seat reproducer
all get the same answer for "the policy on Tuesday".

The lockfile also *records* the generating ``airlock_version``, but
``verify_lock`` does not enforce it: a lock written by 0.6.0 verifies
under 0.8.86 as long as the preset hashes match. It is provenance,
not a constraint, and this docstring said "constraint" until v0.8.86.

Lockfile shape::

    # policy_bundle.lock — generated by airlock <version>
    schema_version = 1
    airlock_version = "0.6.0"
    generated_at = "2026-04-29T09:00:00Z"

    [[preset]]
    preset_id = "mcp_stdio_meta_cve_2026_04"
    content_sha256 = "..."

    [[preset]]
    preset_id = "..."
    content_sha256 = "..."
"""

from __future__ import annotations

import hashlib
import json
import re
from collections.abc import Mapping
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from ..exceptions import AirlockError

LOCK_SCHEMA_VERSION = 1


class LockfileDriftError(AirlockError):
    """Raised when a preset content hash diverges from the lockfile."""

    def __init__(
        self,
        message: str,
        *,
        preset_id: str,
        expected_sha256: str,
        actual_sha256: str,
    ) -> None:
        self.preset_id = preset_id
        self.expected_sha256 = expected_sha256
        self.actual_sha256 = actual_sha256
        super().__init__(message)


class LockfileFormatError(AirlockError):
    """Raised when a lockfile is unparseable or missing required fields."""


class UnstableHashError(AirlockError):
    """Raised when a preset value cannot be hashed reproducibly.

    A lockfile whose hashes differ between processes is worse than no lockfile: it
    verifies green in the run that wrote it and red in every run afterwards, so the
    control looks present while detecting nothing. Refusing is the only honest option.

    Attributes:
        preset_id: The preset being hashed, when the caller supplied one.
        offending: ``repr()`` of the value that could not be hashed stably.
    """

    def __init__(self, message: str, *, preset_id: str | None = None, offending: str = "") -> None:
        self.preset_id = preset_id
        self.offending = offending
        super().__init__(message)


@dataclass(frozen=True)
class LockEntry:
    """One pinned preset row."""

    preset_id: str
    content_sha256: str


@dataclass(frozen=True)
class PolicyBundleLock:
    """Parsed lockfile."""

    schema_version: int
    airlock_version: str
    generated_at: str
    entries: tuple[LockEntry, ...] = field(default_factory=tuple)


# ---------------------------------------------------------------------------
# Hashing
# ---------------------------------------------------------------------------


#: ``<... object at 0x7f...>``. CPython's default ``repr`` embeds the object's address,
#: which differs in every process, so a hash built from it is not reproducible.
_ADDRESS_REPR = re.compile(r" at 0x[0-9a-fA-F]+")

#: Guards against a preset that contains a reference cycle. Presets are configuration, so
#: real nesting is shallow; anything past this is a cycle or a mistake.
_MAX_CANONICAL_DEPTH = 64


def _callable_identity(value: Any) -> str:
    """A process-stable name for a callable.

    ``repr`` of a function carries its address; its qualified name does not, and is the
    same string in every process that imports the same module.
    """
    module = getattr(value, "__module__", "") or ""
    qualname = getattr(value, "__qualname__", "") or getattr(value, "__name__", "")
    return f"{module}.{qualname}" if qualname else repr(value)


def _canonicalise(value: Any, _depth: int = 0) -> Any:
    """Render ``value`` into a JSON-stable canonical form.

    Frozensets, dataclasses, and ``Capability`` enums commonly show up in preset dicts;
    they need explicit handling because ``json.dumps`` does not know how to serialise them.

    Callables need it for a different reason. Guard factories put a closure in the preset
    (``archived_mcp_server_advisory_defaults`` puts one under ``check``), and a function's
    ``repr`` embeds its memory address — so before v0.8.86 such a preset hashed differently
    in every process and ``airlock pack lock --verify`` could never pass. A callable is now
    canonicalised as its qualified name **plus its captured closure values**: the name
    alone would let two differently-parameterised factories collide, which in a drift
    detector is a false negative and worse than the noise it replaced.

    Args:
        value: The value to canonicalise.
        _depth: Recursion depth, used only to fail a cyclic structure loudly.

    Returns:
        A JSON-serialisable structure with deterministic ordering.

    Raises:
        UnstableHashError: If ``value`` nests past :data:`_MAX_CANONICAL_DEPTH`, or if it
            falls through to the ``repr`` path with an address-bearing ``repr``.
    """
    if _depth > _MAX_CANONICAL_DEPTH:
        raise UnstableHashError(
            f"preset value nests deeper than {_MAX_CANONICAL_DEPTH} levels — "
            "a reference cycle cannot be hashed",
            offending=type(value).__name__,
        )
    if isinstance(value, (str, int, float, bool)) or value is None:
        return value
    if isinstance(value, (list, tuple)):
        return [_canonicalise(v, _depth + 1) for v in value]
    if isinstance(value, (set, frozenset)):
        return sorted(_canonicalise(v, _depth + 1) for v in value)
    if isinstance(value, dict):
        return {str(k): _canonicalise(v, _depth + 1) for k, v in sorted(value.items())}
    # Enums (``str, Enum``) carry a ``.value``.
    if hasattr(value, "value") and isinstance(value.value, (str, int, bool)):
        return value.value
    if hasattr(value, "__dataclass_fields__") and not isinstance(value, type):
        from dataclasses import asdict

        return _canonicalise(asdict(value), _depth + 1)
    if callable(value):
        entry: dict[str, Any] = {"__callable__": _callable_identity(value)}
        closure = getattr(value, "__closure__", None)
        if closure:
            captured: list[Any] = []
            for cell in closure:
                try:
                    captured.append(_canonicalise(cell.cell_contents, _depth + 1))
                except ValueError:
                    captured.append(None)  # cell not yet filled
            entry["__closure__"] = captured
        return entry
    rendered = repr(value)
    if _ADDRESS_REPR.search(rendered):
        raise UnstableHashError(
            f"cannot hash {type(value).__name__} reproducibly: its repr() embeds a memory "
            f"address, so the digest would differ in every process. Give the type a stable "
            f"__repr__, make it a dataclass, or keep it out of the preset.",
            offending=rendered,
        )
    return rendered


def hash_preset(preset_data: Any, *, preset_id: str | None = None) -> str:
    """Return the SHA-256 of a preset's canonical JSON form.

    Args:
        preset_data: The preset. Usually a mapping, but guard factories may return a
            dataclass config object, which canonicalises the same way.
        preset_id: Optional id, attached to :class:`UnstableHashError` for a message that
            names the offending preset rather than only the offending type.

    Returns:
        The hex SHA-256 of the canonical JSON encoding.

    Raises:
        UnstableHashError: If any value cannot be hashed reproducibly.
    """
    try:
        canonical = _canonicalise(preset_data)
    except UnstableHashError as exc:
        if preset_id and exc.preset_id is None:
            raise UnstableHashError(
                f"preset {preset_id!r}: {exc}", preset_id=preset_id, offending=exc.offending
            ) from exc
        raise
    encoded = json.dumps(canonical, sort_keys=True, separators=(",", ":")).encode("utf-8")
    return hashlib.sha256(encoded).hexdigest()


# ---------------------------------------------------------------------------
# Generation
# ---------------------------------------------------------------------------


def build_lock(
    preset_data: Mapping[str, Any],
    *,
    airlock_version: str,
    generated_at: datetime | None = None,
) -> PolicyBundleLock:
    """Build a :class:`PolicyBundleLock` from a ``preset_id -> data`` map."""
    when = generated_at or datetime.now(tz=timezone.utc)
    entries = tuple(
        LockEntry(preset_id=pid, content_sha256=hash_preset(data, preset_id=pid))
        for pid, data in sorted(preset_data.items())
    )
    return PolicyBundleLock(
        schema_version=LOCK_SCHEMA_VERSION,
        airlock_version=airlock_version,
        generated_at=when.replace(microsecond=0).isoformat().replace("+00:00", "Z"),
        entries=entries,
    )


def render_lock(lock: PolicyBundleLock) -> str:
    """Render a lockfile to a deterministic TOML string."""
    lines: list[str] = [
        f"# policy_bundle.lock — generated by airlock {lock.airlock_version}",
        f"schema_version = {lock.schema_version}",
        f'airlock_version = "{lock.airlock_version}"',
        f'generated_at = "{lock.generated_at}"',
        "",
    ]
    for entry in lock.entries:
        lines.append("[[preset]]")
        lines.append(f'preset_id = "{entry.preset_id}"')
        lines.append(f'content_sha256 = "{entry.content_sha256}"')
        lines.append("")
    return "\n".join(lines).rstrip("\n") + "\n"


# ---------------------------------------------------------------------------
# Parsing — restricted-grammar TOML (stdlib ``tomllib`` on 3.11+ would work
# too, but we keep a hand-parser to retain support for our 3.10 floor and
# avoid import-cost on the hot path).
# ---------------------------------------------------------------------------


def parse_lock(text: str) -> PolicyBundleLock:
    """Parse a lockfile string into a :class:`PolicyBundleLock`."""
    schema_version: int | None = None
    airlock_version: str | None = None
    generated_at: str | None = None
    entries: list[LockEntry] = []
    current: dict[str, str] = {}
    in_preset = False

    for raw in text.splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if line == "[[preset]]":
            if in_preset and current:
                entries.append(_finalise_entry(current))
            in_preset = True
            current = {}
            continue
        if "=" not in line:
            raise LockfileFormatError(f"unparseable line in lockfile: {raw!r}")
        key, _, value = line.partition("=")
        key = key.strip()
        value = value.strip()
        if value.startswith('"') and value.endswith('"') and len(value) >= 2:
            value = value[1:-1]
        if in_preset:
            current[key] = value
        else:
            if key == "schema_version":
                try:
                    schema_version = int(value)
                except ValueError as exc:
                    raise LockfileFormatError(f"schema_version must be int, got {value!r}") from exc
            elif key == "airlock_version":
                airlock_version = value
            elif key == "generated_at":
                generated_at = value
    if in_preset and current:
        entries.append(_finalise_entry(current))

    if schema_version is None or airlock_version is None or generated_at is None:
        raise LockfileFormatError(
            "lockfile missing required header field "
            "(schema_version / airlock_version / generated_at)"
        )
    if schema_version != LOCK_SCHEMA_VERSION:
        raise LockfileFormatError(
            f"unsupported lockfile schema_version: {schema_version} "
            f"(expected {LOCK_SCHEMA_VERSION})"
        )
    return PolicyBundleLock(
        schema_version=schema_version,
        airlock_version=airlock_version,
        generated_at=generated_at,
        entries=tuple(entries),
    )


def _finalise_entry(d: dict[str, str]) -> LockEntry:
    if "preset_id" not in d or "content_sha256" not in d:
        raise LockfileFormatError(f"preset entry missing preset_id or content_sha256: {d!r}")
    return LockEntry(preset_id=d["preset_id"], content_sha256=d["content_sha256"])


def write_lock(lock: PolicyBundleLock, path: Path) -> None:
    path.write_text(render_lock(lock), encoding="utf-8")


def read_lock(path: Path) -> PolicyBundleLock:
    if not path.exists():
        raise LockfileFormatError(f"lockfile not found: {path}")
    return parse_lock(path.read_text(encoding="utf-8"))


# ---------------------------------------------------------------------------
# Verification
# ---------------------------------------------------------------------------


def verify_lock(
    lock: PolicyBundleLock,
    preset_data: Mapping[str, Any],
) -> None:
    """Raise :class:`LockfileDriftError` on the first hash mismatch."""
    expected = {e.preset_id: e.content_sha256 for e in lock.entries}
    for preset_id, data in preset_data.items():
        if preset_id not in expected:
            raise LockfileDriftError(
                f"preset {preset_id!r} present in bundle but not in lockfile",
                preset_id=preset_id,
                expected_sha256="",
                actual_sha256=hash_preset(data, preset_id=preset_id),
            )
        actual = hash_preset(data, preset_id=preset_id)
        if actual != expected[preset_id]:
            raise LockfileDriftError(
                f"preset {preset_id!r} content hash drifted from lockfile",
                preset_id=preset_id,
                expected_sha256=expected[preset_id],
                actual_sha256=actual,
            )
    bundle_ids = set(preset_data)
    for entry in lock.entries:
        if entry.preset_id not in bundle_ids:
            raise LockfileDriftError(
                f"preset {entry.preset_id!r} listed in lockfile but missing from current bundle",
                preset_id=entry.preset_id,
                expected_sha256=entry.content_sha256,
                actual_sha256="",
            )


__all__ = [
    "LOCK_SCHEMA_VERSION",
    "LockEntry",
    "LockfileDriftError",
    "LockfileFormatError",
    "PolicyBundleLock",
    "UnstableHashError",
    "build_lock",
    "hash_preset",
    "parse_lock",
    "read_lock",
    "render_lock",
    "verify_lock",
    "write_lock",
]
