#!/usr/bin/env python3
"""Regenerate the ``TEST-BADGE`` block in README.md (v0.5.3+).

Idempotent. Runs pytest in coverage mode, parses the collected-test
count and the TOTAL coverage percentage, and rewrites the block
between the ``<!-- TEST-BADGE-START -->`` / ``<!-- TEST-BADGE-END -->``
HTML-comment markers.

Usage::

    python3 scripts/update_test_badge.py           # rewrite in place
    python3 scripts/update_test_badge.py --check   # exit non-zero on drift

Exit codes:
    0 — block is up-to-date (or was rewritten successfully in normal mode)
    1 — drift detected (``--check`` only)
    2 — markers missing or pytest failed
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
README = ROOT / "README.md"
START = "<!-- TEST-BADGE-START -->"
END = "<!-- TEST-BADGE-END -->"

BADGE_TEMPLATE = """{start}
<!-- Auto-generated by scripts/update_test_badge.py. Do not edit by hand. -->
**Test suite:** {total:,} tests · **Coverage:** {coverage} · **v{version}**<br>
<sub>Coverage runs {run:,} of {total:,}; the {excluded} excluded are \
{benchmarks} benchmark tests (not correctness tests) and {docker} docker-marked \
(need a daemon).</sub>
{end}"""


def _collect_count(extra_args: list[str]) -> tuple[int, int]:
    """Return ``(collected, deselected)`` from a fast ``--collect-only`` run.

    ``collected`` is the number pytest reports before the ``-m`` marker filter runs
    (its "N tests collected" figure); ``deselected`` is the ``(N deselected)`` count,
    0 when absent. No tests execute, so this is cheap.
    """
    result = subprocess.run(
        [sys.executable, "-m", "pytest", "--collect-only", "-q", "--no-cov", *extra_args],
        check=False,
        capture_output=True,
        text=True,
        cwd=ROOT,
    )
    if result.returncode not in (0, 5):  # 5 == "no tests collected", tolerated
        print(result.stdout, file=sys.stderr)
        print(result.stderr, file=sys.stderr)
        sys.exit(2)
    collected_m = re.search(r"(\d+)\s+tests collected", result.stdout)
    if not collected_m:
        if "no tests collected" in result.stdout:
            return 0, 0
        print("could not parse pytest collected-test count", file=sys.stderr)
        print(result.stdout, file=sys.stderr)
        sys.exit(2)
    deselected_m = re.search(r"\((\d+)\s+deselected\)", result.stdout)
    return int(collected_m.group(1)), int(deselected_m.group(1)) if deselected_m else 0


def _run_pytest() -> tuple[int, int, int, int, str]:
    """Return ``(total, run, docker_excluded, benchmark_excluded, coverage_str)``.

    The headline count must be the WHOLE suite, not just what the coverage run
    exercises. ``addopts`` applies ``--ignore=tests/benchmarks`` and ``-m 'not
    docker'``, so the default collect omits the benchmark tests and reports the
    docker-marked ones as *deselected*; a second, unfiltered collect gives the true
    total, and the benchmark bucket is the difference. Both are ``--collect-only``
    runs (no execution), so this adds ~1.5s and does not meaningfully slow anything.
    Counts are for the standard dev env (``.[dev]``); optional-extra tests gated by
    ``importorskip`` skip identically here and in CI.
    """
    filtered_collected, docker_excluded = _collect_count([])
    total, _ = _collect_count(["-o", "addopts="])
    benchmark_excluded = total - filtered_collected
    run = filtered_collected - docker_excluded

    # Full run with coverage to get the TOTAL line.
    cov = subprocess.run(
        [sys.executable, "-m", "pytest", "-q"],
        check=False,
        capture_output=True,
        text=True,
        cwd=ROOT,
    )
    # We accept non-zero return (tests could fail) but require a
    # parseable coverage line. If there isn't one we exit non-zero so
    # the pre-release checklist notices.
    output = cov.stdout + "\n" + cov.stderr
    cov_m = re.search(r"Total coverage:\s*(\d+\.\d+%)", output)
    if not cov_m:
        cov_m = re.search(r"^TOTAL\s+.*?(\d+%)\s*$", output, re.MULTILINE)
    if not cov_m:
        print("could not parse pytest coverage total", file=sys.stderr)
        print(output[-2000:], file=sys.stderr)
        sys.exit(2)
    coverage = cov_m.group(1)
    return total, run, docker_excluded, benchmark_excluded, coverage


def _read_version() -> str:
    init = (ROOT / "src" / "agent_airlock" / "__init__.py").read_text()
    m = re.search(r'__version__\s*=\s*"([^"]+)"', init)
    if not m:
        print("could not find __version__", file=sys.stderr)
        sys.exit(2)
    return m.group(1)


def _rewrite(readme_text: str, block: str) -> str:
    pattern = re.compile(
        re.escape(START) + r".*?" + re.escape(END),
        flags=re.DOTALL,
    )
    if pattern.search(readme_text):
        return pattern.sub(block, readme_text)
    # Markers absent — caller must add them once manually; we don't
    # auto-insert, because placement is editorial.
    print(
        f"README is missing the TEST-BADGE block. Insert these markers "
        f"wherever you want the badge, then re-run this script:\n"
        f"  {START}\n  {END}",
        file=sys.stderr,
    )
    sys.exit(2)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero if README drifts from the generator output",
    )
    args = parser.parse_args()

    total, run, docker, benchmarks, coverage = _run_pytest()
    version = _read_version()
    block = BADGE_TEMPLATE.format(
        start=START,
        end=END,
        total=total,
        run=run,
        docker=docker,
        benchmarks=benchmarks,
        excluded=docker + benchmarks,
        coverage=coverage,
        version=version,
    )

    current = README.read_text()
    updated = _rewrite(current, block)

    if args.check:
        if current != updated:
            print(
                "README TEST-BADGE block is stale. Run `make test-badge` to refresh it.",
                file=sys.stderr,
            )
            return 1
        return 0

    README.write_text(updated)
    print(
        f"wrote {total:,} tests ({run:,} run, {docker + benchmarks} excluded: "
        f"{benchmarks} benchmark + {docker} docker) · {coverage} · v{version}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
