#!/usr/bin/env python3
"""Regenerate the ``TEST-BADGE`` block in README.md (v0.5.3+).

Idempotent. Runs pytest in coverage mode, parses the collected-test
count and the TOTAL coverage percentage, and rewrites the block
between the ``<!-- TEST-BADGE-START -->`` / ``<!-- TEST-BADGE-END -->``
HTML-comment markers.

Usage::

    python3 scripts/update_test_badge.py           # rewrite in place
    python3 scripts/update_test_badge.py --check   # exit non-zero on drift

Exit codes:
    0 — block is up-to-date (or was rewritten successfully in normal mode)
    1 — drift detected (``--check`` only)
    2 — markers missing or pytest failed
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
README = ROOT / "README.md"
START = "<!-- TEST-BADGE-START -->"
END = "<!-- TEST-BADGE-END -->"

BADGE_TEMPLATE = """{start}
<!-- Auto-generated by scripts/update_test_badge.py. Do not edit by hand. -->
**Test suite:** {tests:,} tests · **Coverage:** {coverage} · **v{version}**
{end}"""


def _run_pytest() -> tuple[int, str]:
    """Return (collected_test_count, coverage_total_str)."""
    # 1. Collect count without running — fast and cheap.
    collect = subprocess.run(
        [sys.executable, "-m", "pytest", "--collect-only", "-q", "--no-cov"],
        check=False,
        capture_output=True,
        text=True,
        cwd=ROOT,
    )
    if collect.returncode != 0:
        print(collect.stdout, file=sys.stderr)
        print(collect.stderr, file=sys.stderr)
        sys.exit(2)
    m = re.search(r"(\d+)\s+tests collected", collect.stdout)
    if not m:
        print("could not parse pytest collected-test count", file=sys.stderr)
        sys.exit(2)
    tests = int(m.group(1))

    # 2. Full run with coverage to get the TOTAL line.
    cov = subprocess.run(
        [sys.executable, "-m", "pytest", "-q"],
        check=False,
        capture_output=True,
        text=True,
        cwd=ROOT,
    )
    # We accept non-zero return (tests could fail) but require a
    # parseable coverage line. If there isn't one we exit non-zero so
    # the pre-release checklist notices.
    output = cov.stdout + "\n" + cov.stderr
    cov_m = re.search(r"Total coverage:\s*(\d+\.\d+%)", output)
    if not cov_m:
        cov_m = re.search(r"^TOTAL\s+.*?(\d+%)\s*$", output, re.MULTILINE)
    if not cov_m:
        print("could not parse pytest coverage total", file=sys.stderr)
        print(output[-2000:], file=sys.stderr)
        sys.exit(2)
    coverage = cov_m.group(1)
    return tests, coverage


def _read_version() -> str:
    init = (ROOT / "src" / "agent_airlock" / "__init__.py").read_text()
    m = re.search(r'__version__\s*=\s*"([^"]+)"', init)
    if not m:
        print("could not find __version__", file=sys.stderr)
        sys.exit(2)
    return m.group(1)


def _rewrite(readme_text: str, block: str) -> str:
    pattern = re.compile(
        re.escape(START) + r".*?" + re.escape(END),
        flags=re.DOTALL,
    )
    if pattern.search(readme_text):
        return pattern.sub(block, readme_text)
    # Markers absent — caller must add them once manually; we don't
    # auto-insert, because placement is editorial.
    print(
        f"README is missing the TEST-BADGE block. Insert these markers "
        f"wherever you want the badge, then re-run this script:\n"
        f"  {START}\n  {END}",
        file=sys.stderr,
    )
    sys.exit(2)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="exit non-zero if README drifts from the "
                        "generator output")
    args = parser.parse_args()

    tests, coverage = _run_pytest()
    version = _read_version()
    block = BADGE_TEMPLATE.format(
        start=START,
        end=END,
        tests=tests,
        coverage=coverage,
        version=version,
    )

    current = README.read_text()
    updated = _rewrite(current, block)

    if args.check:
        if current != updated:
            print(
                "README TEST-BADGE block is stale. "
                "Run `make test-badge` to refresh it.",
                file=sys.stderr,
            )
            return 1
        return 0

    README.write_text(updated)
    print(f"wrote {tests:,} tests · {coverage} · v{version}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
